### ISSUE TITLE
[Merged on GitLab] Change `provider_id` column string length from 50 to 250

### ISSUE THREAD

**Issue by sf-chris** [Sportsflare/bass-tube#145]
closes #30

*Originally created on GitLab as an MR by matt.cavill (https://gitlab.com/sportsflare/real-time/bass-tube/-/merge_requests/30) on 2022-03-28T23:17:50.910Z*

**Comment by sf-chris** [comment]
Very good, thanks bro

*Originally commented on GitLab by matt.cavill on 2022-03-29T01:58:03.029Z*

**Comment by sf-chris** [comment]
`black` just released an update to work with Click `8.1.0`

https://github.com/psf/black/releases/tag/22.3.0

Try upgrading our `black` version and try again

*Originally commented on GitLab by steffansafey on 2022-03-29T01:30:49.047Z*

**Comment by sf-chris** [comment]
``` from click import _unicodefun  # type: ignore
271ImportError: cannot import name '_unicodefun' from 'click' (/usr/local/lib/python3.8/site-packages/click/__init__.py) ```

*Originally commented on GitLab by matt.cavill on 2022-03-28T23:33:27.034Z*

**Comment by sf-chris** [comment]
Not sure what is going on with lint here.. local works but gitlab doesn't.

*Originally commented on GitLab by matt.cavill on 2022-03-28T23:31:52.997Z*
